# Generated by Django 3.0 on 2024-02-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('coursestartdate', models.DateField()),
                ('courseenddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('studentemail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.AutoField(primary_key=True, serialize=False)),
                ('teacheremail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('studentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Student')),
                ('teacherid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
