# Generated by Django 3.0 on 2024-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentFirstName',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='studentLastName',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherFirstName',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherLastName',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
