# Generated by Django 3.0 on 2024-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0003_course_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursecode',
            field=models.CharField(default='A123', max_length=4),
        ),
    ]
