# Generated by Django 3.0 on 2024-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0004_course_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursecode',
            field=models.CharField(max_length=4),
        ),
    ]
