# Generated by Django 3.0 on 2024-02-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0006_course_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='a',
        ),
    ]
