# Generated by Django 3.0 on 2024-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0008_courseenrollment_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='a',
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback',
            field=models.TextField(max_length=200),
        ),
    ]
