# Generated by Django 3.0 on 2024-03-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0011_auto_20240306_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='files',
        ),
    ]
