# Generated by Django 3.0 on 2024-03-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0012_auto_20240306_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='courseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalprojapp.Course'),
        ),
    ]
