# Generated by Django 3.0 on 2024-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0014_auto_20240308_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=20),
        ),
    ]
