# Generated by Django 3.0 on 2024-03-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojapp', '0016_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='course',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='studentid',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
